languageCode:           "en"
title:                  "Bootstrap"
baseURL:                "https://v5.getbootstrap.com"
enableInlineShortcodes: true

module:
  mounts:
    - source:           web
      target:           build/index.html
      
   - source:           404
     target:           404.html
