languageCode:           "en"
title:                  "PHP Sample"
baseURL:                "https://zeeforumcompany.github.io/php-sample"
enableInlineShortcodes: true

module:
  mounts:
    - source:           build
      target:           content
    - source:           build/static/css/2.f3cffc9e.chunk.css
      target:           https://zeeforumcompany.github.io/static/css/2.f3cffc9e.chunk.css
    - source:           build/static/css/main.5f361e03.chunk.css
      target:           https://zeeforumcompany.github.io/static/css/main.5f361e03.chunk.css
    - source:           build/static/js/2.0dd7b655.chunk.js
      target:           https://zeeforumcompany.github.io/static/js/2.0dd7b655.chunk.js
    - source:           build/static/js/main.bca22e11.chunk.js
      target:           https://zeeforumcompany.github.io/static/js/main.bca22e11.chunk.js
