languageCode:           "en"
title:                  "PHP Sample"
baseURL:                "https://zeeforumcompany.github.io/php-sample"
enableInlineShortcodes: true

module:
  mounts:
    - source:           build
      target:           content
